"""001_base_version

Revision ID: 001_base_version
Revises: None
Create Date: 2026-06-26 23:14:12.006971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001_base_version'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('supabase_user_id', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('STUDENT', 'MENTOR', 'HOD', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_supabase_user_id'), 'users', ['supabase_user_id'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('mentors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('max_mentees', sa.Integer(), nullable=True),
    sa.Column('mobile_no', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_mentors_id'), 'mentors', ['id'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('usn', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('student_mobile', sa.String(), nullable=True),
    sa.Column('parent_mobile', sa.String(), nullable=True),
    sa.Column('parent_email', sa.String(), nullable=True),
    sa.Column('attendance_rate', sa.Float(), nullable=True),
    sa.Column('cgpa', sa.Float(), nullable=True),
    sa.Column('sgpa', sa.Float(), nullable=True),
    sa.Column('success_score', sa.Float(), nullable=True),
    sa.Column('risk_status', sa.String(), nullable=True),
    sa.Column('consent_given', sa.Boolean(), nullable=True),
    sa.Column('is_under_18', sa.Boolean(), nullable=False),
    sa.Column('mentor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mentor_id'], ['mentors.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_students_id'), 'students', ['id'], unique=False)
    op.create_index(op.f('ix_students_usn'), 'students', ['usn'], unique=True)
    op.create_table('attendance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('subject_code', sa.String(length=50), nullable=False),
    sa.Column('subject_name', sa.String(length=255), nullable=True),
    sa.Column('total_classes', sa.Integer(), nullable=False),
    sa.Column('attended_classes', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'subject_code', 'period', name='uq_attendance_student_subject_period')
    )
    op.create_index(op.f('ix_attendance_records_id'), 'attendance_records', ['id'], unique=False)
    op.create_index(op.f('ix_attendance_records_period'), 'attendance_records', ['period'], unique=False)
    op.create_index(op.f('ix_attendance_records_student_id'), 'attendance_records', ['student_id'], unique=False)
    op.create_table('lms_activity_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('login_count', sa.Integer(), nullable=True),
    sa.Column('assignments_submitted', sa.Integer(), nullable=True),
    sa.Column('assignments_total', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'period', name='uq_lms_student_period')
    )
    op.create_index(op.f('ix_lms_activity_records_id'), 'lms_activity_records', ['id'], unique=False)
    op.create_index(op.f('ix_lms_activity_records_period'), 'lms_activity_records', ['period'], unique=False)
    op.create_index(op.f('ix_lms_activity_records_student_id'), 'lms_activity_records', ['student_id'], unique=False)
    op.create_table('meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mentor_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('mode', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['mentor_id'], ['mentors.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meetings_id'), 'meetings', ['id'], unique=False)
    op.create_table('placement_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('has_resume', sa.Boolean(), nullable=True),
    sa.Column('skills_count', sa.Integer(), nullable=True),
    sa.Column('certifications_count', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_placement_profiles_id'), 'placement_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_placement_profiles_student_id'), 'placement_profiles', ['student_id'], unique=True)
    op.create_table('student_consents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('academic', 'attendance', 'placement', 'wellness', name='consentcategory'), nullable=False),
    sa.Column('consented', sa.Boolean(), nullable=False),
    sa.Column('notice_version', sa.String(), nullable=False),
    sa.Column('consented_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'category', name='uq_student_consent_category')
    )
    op.create_index(op.f('ix_student_consents_id'), 'student_consents', ['id'], unique=False)
    op.create_index(op.f('ix_student_consents_student_id'), 'student_consents', ['student_id'], unique=False)
    op.create_table('student_success_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('attendance_component', sa.Float(), nullable=True),
    sa.Column('academic_component', sa.Float(), nullable=True),
    sa.Column('engagement_component', sa.Float(), nullable=True),
    sa.Column('placement_component', sa.Float(), nullable=True),
    sa.Column('total_score', sa.Float(), nullable=True),
    sa.Column('risk_category', sa.String(length=20), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=True),
    sa.Column('period', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_student_computed', 'student_success_scores', ['student_id', 'computed_at'], unique=False)
    op.create_index(op.f('ix_student_success_scores_computed_at'), 'student_success_scores', ['computed_at'], unique=False)
    op.create_index(op.f('ix_student_success_scores_id'), 'student_success_scores', ['id'], unique=False)
    op.create_index(op.f('ix_student_success_scores_student_id'), 'student_success_scores', ['student_id'], unique=False)
    op.create_table('meeting_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('topics_discussed', sa.JSON(), nullable=False),
    sa.Column('action_items', sa.JSON(), nullable=False),
    sa.Column('next_meeting_date', sa.Date(), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('logged_at', sa.DateTime(), nullable=False),
    sa.Column('logged_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['logged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id')
    )
    op.create_index(op.f('ix_meeting_logs_id'), 'meeting_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meeting_logs_id'), table_name='meeting_logs')
    op.drop_table('meeting_logs')
    op.drop_index(op.f('ix_student_success_scores_student_id'), table_name='student_success_scores')
    op.drop_index(op.f('ix_student_success_scores_id'), table_name='student_success_scores')
    op.drop_index(op.f('ix_student_success_scores_computed_at'), table_name='student_success_scores')
    op.drop_index('idx_student_computed', table_name='student_success_scores')
    op.drop_table('student_success_scores')
    op.drop_index(op.f('ix_student_consents_student_id'), table_name='student_consents')
    op.drop_index(op.f('ix_student_consents_id'), table_name='student_consents')
    op.drop_table('student_consents')
    op.drop_index(op.f('ix_placement_profiles_student_id'), table_name='placement_profiles')
    op.drop_index(op.f('ix_placement_profiles_id'), table_name='placement_profiles')
    op.drop_table('placement_profiles')
    op.drop_index(op.f('ix_meetings_id'), table_name='meetings')
    op.drop_table('meetings')
    op.drop_index(op.f('ix_lms_activity_records_student_id'), table_name='lms_activity_records')
    op.drop_index(op.f('ix_lms_activity_records_period'), table_name='lms_activity_records')
    op.drop_index(op.f('ix_lms_activity_records_id'), table_name='lms_activity_records')
    op.drop_table('lms_activity_records')
    op.drop_index(op.f('ix_attendance_records_student_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_period'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_id'), table_name='attendance_records')
    op.drop_table('attendance_records')
    op.drop_index(op.f('ix_students_usn'), table_name='students')
    op.drop_index(op.f('ix_students_id'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_mentors_id'), table_name='mentors')
    op.drop_table('mentors')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_supabase_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
