"""add profile_picture_url to students

Revision ID: fcd3bdb2b30b
Revises: 1aa377368443
Create Date: 2026-07-13 17:49:20.972616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcd3bdb2b30b'
down_revision: Union[str, None] = '1aa377368443'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_allocations_student_id'), table_name='allocations')
    op.add_column('students', sa.Column('profile_picture_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'profile_picture_url')
    op.create_index(op.f('ix_allocations_student_id'), 'allocations', ['student_id'], unique=False)
    # ### end Alembic commands ###
